### ISSUE TITLE
values in vars files are not resolved into credhub 

### ISSUE THREAD

**Issue by sjolicoeur** [pivotal-cf/credhub-release#26]
What version of the credhub server you are using?

1.95

What version of the credhub cli you are using?
2.0.0 ( has little bearing to the issue, I think )

If you were attempting to accomplish a task, what was it you were attempting to do?

I was attempting to deploy a new CF

What did you expect to happen?

I expected any missing certs to get autogenerated

What was the actual behavior?
the missing certs failed to auto generate with the error:
```Error: Config Server failed to generate value for '/bosh-bbl-env-qinghai-2017-09-05t21-24z/cf/cc_public_tls' with type 'certificate'. HTTP Code '404', Error: 'The request could not be completed because the credential does not exist or you do not have sufficient authorization.'```

at the time this happened we were in transition and using both a `vars` and credhub. And I do understand that because our CA was defined in the `vars` file credhub was not able to see it, and thus unable to generate the certs. That said having an error point directly to that fact in some way would have avoided a lot of the efforts put in to debug this.  I was told that the reasoning for such a vague error was due to security  concerns, but I view this type of error as a compilation error, and the error should provide more context as to what happened and what actions could be taken to resolve the issue. ( accept variable resolution from the vars file into credhub... but that would be a behavior change. ) 

I think making the errors more actionable and at the very least give more context into what went wrong, while balancing security would lessen operational burden imposed on operator.

Thank you,

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

[1] https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1533756359000048
[2] https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1533837835000255

**Comment by amuessig** [comment]
I have the same issue with passwords.

**Comment by athornton2012** [comment]
@sjolicoeur @amuessig This seems like a BOSH issue to me. CredHub does not have any knowledge of the context in which your cert is being created. It is error-ing because there was not CA that it knew about to sign the cert you are asking it to create. BOSH holds all the cards in that it should be responsible for seeing the CredHub could not create the cert and telling you why. Closing. Feel free to reopen if you disagree.

**Comment by emalm** [comment]
Hey, @athornton2012, I agree that BOSH could do more to provide context here, but this is fundamentally an issue with the vague error coming from the CredHub API. In this case, BOSH requested that this new certificate be issued with a reference to a CA cert named `/bosh-bbl-env-qinghai-2017-09-05t21-24z/cf/service_cf_internal_ca` that it though CredHub would have, but didn't. It's possible to generate the same error via the CredHub CLI when generating a certificate entry against a reference to a CA cert that does not exist:

```
$ credhub generate -n /cert -t certificate --ca /ca-not-there -c cert
The request could not be completed because the credential does not exist or you do not have sufficient authorization.
```

In general, it would be clearer for the error message to refer to the name of the certificate credential that doesn't exist: `The request could not be completed because the credential '/ca-not-there' does not exist or you do not have sufficient authorization.` Otherwise, the user is inclined to think that the credential that doesn't exist is the one they are trying to generate, which is especially confusing because of course that credential doesn't exist yet before it has been generated.

In any case, the non-specificity of this error tied up a pair on the Diego team for about a day while they figured out the reason behind it. I expect they would have figured it out much faster if the error message had specified the precise credential that didn't exist. I don't think there's a concern here about leaking information, because the client already knows that CA credential name, and they presumably see this error if it does exist but the client isn't authorized to read it.

Thanks,
Eric

**Comment by athornton2012** [comment]
@emalm Hm okay, that seems like a good point. There is no need to obscure the credential name that CredHub was unable to find. Also I can see how this would be really annoying (it happened to me a couple days ago). Thanks for your comment!

**Comment by ankeesler** [comment]
Hey folks, this should be fixed in the latest release of CredHub! Here is the story we did to make error messages a little better: https://www.pivotaltracker.com/n/projects/1977341/stories/161087845.
